import { errorResponse, jsonResponse } from '../_utils/response.js'

const MAX_MESSAGE_LENGTH = 4000
const MAX_HISTORY_MESSAGES = 20
const MAX_HISTORY_MESSAGE_LENGTH = 2000

const modeInstructions = {
  balanced: 'Use a balanced, clear and helpful tone.',
  creative: 'Be more imaginative, exploratory and open-ended while staying useful.',
  precise: 'Be direct, concise and careful. Avoid unnecessary detail.',
  friendly: 'Be warm, conversational and encouraging.',
  technical: 'Use more technical detail. Include code examples when they are useful.',
}

function getSystemPrompt(mode) {
  return [
    'You are Nova, a helpful general-purpose AI chatbot.',
    'You can discuss a wide range of topics, explain concepts clearly, help with writing, brainstorming, coding, planning and general questions.',
    'Be concise, useful and safe.',
    'Do not claim to be human.',
    'If you are unsure, say so.',
    modeInstructions[mode] || modeInstructions.balanced,
  ].join(' ')
}

async function readJson(request) {
  try {
    return await request.json()
  } catch {
    return null
  }
}

function normalizeMode(mode) {
  const cleanMode = String(mode || 'balanced').toLowerCase()
  return modeInstructions[cleanMode] ? cleanMode : 'balanced'
}

function normalizeMessageItem(item) {
  const role = item?.role === 'assistant' ? 'assistant' : 'user'
  const content = String(item?.content || '').slice(0, MAX_HISTORY_MESSAGE_LENGTH)
  return content.trim() ? { role, content } : null
}

function normalizeHistory(messages) {
  if (!Array.isArray(messages)) return []
  return messages
    .slice(-MAX_HISTORY_MESSAGES)
    .map(normalizeMessageItem)
    .filter(Boolean)
}

function createDemoReply(message, mode) {
  const cleanMessage = message.toLowerCase()
  const styleNote = {
    balanced: 'Here is a balanced demo answer.',
    creative: 'Here is a more creative demo answer.',
    precise: 'Here is a concise demo answer.',
    friendly: 'Here is a friendly demo answer.',
    technical: 'Here is a more technical demo answer.',
  }[mode] || 'Here is a demo answer.'

  if (/\b(hello|hi|hey)\b/.test(cleanMessage)) {
    return `${styleNote}\n\nHi! I am Nova running in demo mode. You can test the chat interface, response modes, quick prompts, copy actions and session history here.`
  }

  if (cleanMessage.includes('explain')) {
    return `${styleNote}\n\nA good explanation usually works best in three parts:\n\n1. Start with the simple idea.\n2. Add a practical example.\n3. Mention the limitation or trade-off.\n\nDemo mode is active, so this response is rule-based instead of generated by a live AI provider.`
  }

  if (cleanMessage.includes('idea') || cleanMessage.includes('project')) {
    return `${styleNote}\n\nHere are a few project ideas:\n\n- Build a personal habit tracker with charts.\n- Create a small recipe search app with filters.\n- Make a local note-taking tool with tags.\n- Design a dashboard that explains API status clearly.\n\nPick one with a small scope and finish the full flow.`
  }

  if (cleanMessage.includes('email')) {
    return `${styleNote}\n\nSubject: Quick follow-up\n\nHi,\n\nI hope you are doing well. I wanted to follow up and share a quick update. Please let me know if you need any additional information.\n\nBest regards,\nNova`
  }

  if (cleanMessage.includes('javascript') || cleanMessage.includes('code')) {
    return `${styleNote}\n\nIn JavaScript, it often helps to separate data, state and rendering. For example:\n\n\`\`\`js\nconst items = data.filter((item) => item.active)\nconst labels = items.map((item) => item.name)\n\`\`\`\n\nThis keeps each step easier to read and debug.`
  }

  if (cleanMessage.includes('workout')) {
    return `${styleNote}\n\nBeginner workout idea:\n\n- 5 minutes warm-up walk\n- 3 rounds of bodyweight squats, push-ups and planks\n- 10 minutes easy cardio\n- Stretch for 5 minutes\n\nStart gently and adapt to your fitness level.`
  }

  if (cleanMessage.includes('story')) {
    return `${styleNote}\n\nA small satellite woke up above a blue planet and realized it had forgotten its mission. Every orbit, it collected one tiny sound from Earth until the sounds became a map. By sunrise, it understood: it was not there to watch the world, but to remember it.`
  }

  return `${styleNote}\n\nDemo mode is active because no AI API key is configured. I can still simulate a useful answer, but a real provider would generate a more flexible response.\n\nYou asked: "${message.slice(0, 240)}${message.length > 240 ? '...' : ''}"`
}

async function callOpenAI(env, messages, mode) {
  const model = env.AI_MODEL || 'gpt-4o-mini'
  const response = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${env.AI_API_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model,
      messages: [
        { role: 'system', content: getSystemPrompt(mode) },
        ...messages,
      ],
      temperature: mode === 'creative' ? 0.9 : mode === 'precise' ? 0.2 : 0.6,
    }),
  })

  const data = await response.json().catch(() => null)
  if (!response.ok) {
    throw new Error(data?.error?.message || 'OpenAI request failed.')
  }

  return {
    reply: data?.choices?.[0]?.message?.content || '',
    provider: 'openai',
    model,
  }
}

async function callAnthropic(env, messages, mode) {
  const model = env.AI_MODEL || 'claude-3-5-haiku-latest'
  const response = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'x-api-key': env.AI_API_KEY,
      'anthropic-version': '2023-06-01',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model,
      max_tokens: 900,
      system: getSystemPrompt(mode),
      messages,
    }),
  })

  const data = await response.json().catch(() => null)
  if (!response.ok) {
    throw new Error(data?.error?.message || 'Anthropic request failed.')
  }

  return {
    reply: data?.content?.map((part) => part.text).filter(Boolean).join('\n') || '',
    provider: 'anthropic',
    model,
  }
}

async function callCloudflareAI(env, messages, mode) {
  if (!env.AI) throw new Error('Cloudflare AI binding is not configured.')
  const model = env.AI_MODEL || '@cf/meta/llama-3.1-8b-instruct'
  const result = await env.AI.run(model, {
    messages: [
      { role: 'system', content: getSystemPrompt(mode) },
      ...messages,
    ],
  })

  return {
    reply: result?.response || result?.result?.response || '',
    provider: 'cloudflare-ai',
    model,
  }
}

export async function onRequestPost(context) {
  const { request, env } = context
  const body = await readJson(request)
  if (!body) return errorResponse('Invalid JSON payload.', 400)

  const message = String(body.message || '').trim()
  if (!message) return errorResponse('Message is required.', 400)
  if (message.length > MAX_MESSAGE_LENGTH) {
    return errorResponse(`Message is too long. Maximum length is ${MAX_MESSAGE_LENGTH} characters.`, 400)
  }

  const mode = normalizeMode(body.mode)
  const history = normalizeHistory(body.messages)
  const provider = String(env.AI_PROVIDER || 'demo').toLowerCase()
  const messages = [...history, { role: 'user', content: message }].slice(-MAX_HISTORY_MESSAGES)
  const supportedProviders = ['demo', 'openai', 'anthropic', 'cloudflare-ai']

  if (!supportedProviders.includes(provider)) {
    return errorResponse('Unsupported AI provider', 400)
  }

  if (!env.AI_API_KEY && provider !== 'cloudflare-ai') {
    return jsonResponse({
      ok: true,
      reply: createDemoReply(message, mode),
      mode,
      provider: 'demo',
      model: 'demo-rule-based',
      demoMode: true,
    })
  }

  if (provider === 'demo') {
    return jsonResponse({
      ok: true,
      reply: createDemoReply(message, mode),
      mode,
      provider: 'demo',
      model: 'demo-rule-based',
      demoMode: true,
    })
  }

  try {
    let result
    if (provider === 'openai') result = await callOpenAI(env, messages, mode)
    else if (provider === 'anthropic') result = await callAnthropic(env, messages, mode)
    else if (provider === 'cloudflare-ai') result = await callCloudflareAI(env, messages, mode)

    if (!result.reply) return errorResponse('AI provider returned an empty response.', 502)

    return jsonResponse({
      ok: true,
      reply: result.reply,
      mode,
      provider: result.provider,
      model: result.model,
      demoMode: false,
    })
  } catch (error) {
    return errorResponse('Nova could not answer right now. Please try again in a moment.', 502, String(error?.message || 'AI request failed.'))
  }
}
